# Generated by Django 3.1.3 on 2020-11-12 08:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('branchID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project.user')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phonenumber', models.CharField(max_length=10)),
                ('emirates', models.CharField(max_length=14)),
                ('capacity', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project.user')),
                ('name', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('taskID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
                ('fromBranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.branches')),
                ('toBank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.branches')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project.user')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('phonenumber', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('emirates', models.CharField(max_length=14)),
                ('dob', models.CharField(max_length=10)),
                ('currenttask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.tasks')),
            ],
        ),
        migrations.AddField(
            model_name='branches',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.outlet'),
        ),
    ]
