# Generated by Django 3.1.3 on 2020-11-12 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='currenttask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.tasks'),
        ),
    ]
