# Generated by Django 3.1.3 on 2020-11-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20201112_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isValid',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
